/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prak_alproii_pertemuan8_modul7;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrameUpdateDelete extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/manajemen_jadwal";

    DefaultTableModel mod;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i;

    /**
     * Creates new form FrameUpdateDelete
     */
    public FrameUpdateDelete() {
        initComponents();
    }

    public void getdata(String ls_maskapai, String ls_dari, String ls_menuju, String ls_berangkat, String ls_tiba, String rdTipe, String ls_harga) {
        cbMaskapai.setSelectedItem(ls_maskapai);
        cbDari.setSelectedItem(ls_dari);
        cbMenuju.setSelectedItem(ls_menuju);
        txtBerangkat.setText(ls_berangkat);
        txtTiba.setText(ls_tiba);

        switch (rdTipe) {
            case "Ekonomi":
                rdEkonomi.setSelected(true);
                break;
            case "Bisnis":
                rdBisnis.setSelected(true);
                break;
            case "Eksekutif":
                rdEksekutif.setSelected(true);
                break;
            default:
                break;
        }

        txtHarga.setText(ls_harga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdTipe = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbMaskapai = new javax.swing.JComboBox<>();
        cbDari = new javax.swing.JComboBox<>();
        cbMenuju = new javax.swing.JComboBox<>();
        txtBerangkat = new javax.swing.JTextField();
        txtTiba = new javax.swing.JTextField();
        rdEkonomi = new javax.swing.JRadioButton();
        rdBisnis = new javax.swing.JRadioButton();
        rdEksekutif = new javax.swing.JRadioButton();
        txtHarga = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setText("Maskapai");

        jLabel3.setText("Dari");

        jLabel4.setText("Menuju");

        jLabel5.setText("Berangkat");

        jLabel6.setText("Tiba");

        jLabel7.setText("Tipe");

        jLabel8.setText("Harga");

        cbMaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garuda Indonesia", "Air Asia", "Sriwijaya Air", "Lion Air", "Dulinan Air" }));

        cbDari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandar Udara Internasional Soekarno-Hatta", "Bandar Udara Internasional Ngurah Rai", "Bandar Udara Internasional Juanda" }));

        cbMenuju.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandar Udara Internasionall Sultan Hasanuddin", "Bandar Udara Internasional Kualanamu", "Bandar Udara Internasional Lombok", "Eternity" }));

        rdTipe.add(rdEkonomi);
        rdEkonomi.setText("Ekonomi");

        rdTipe.add(rdBisnis);
        rdBisnis.setText("Bisnis");

        rdTipe.add(rdEksekutif);
        rdEksekutif.setText("Eksekutif");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdEkonomi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBisnis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdEksekutif))
                    .addComponent(cbMaskapai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMenuju, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBerangkat)
                    .addComponent(txtHarga)
                    .addComponent(txtTiba))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMenuju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTiba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdEkonomi)
                    .addComponent(rdBisnis)
                    .addComponent(rdEksekutif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(33, 33, 33)
                .addComponent(btnHapus)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnKembali))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here
        String ls_maskapai = cbMaskapai.getSelectedItem().toString();
        String ls_dari = cbDari.getSelectedItem().toString();
        String ls_menuju = cbMenuju.getSelectedItem().toString();
        String ls_berangkat = txtBerangkat.getText();
        String ls_tiba = txtTiba.getText();
        String rdTipe = "";
        if (rdEkonomi.isSelected()) {
            rdTipe = rdEkonomi.getText();
        } else if (rdBisnis.isSelected()) {
            rdTipe = rdBisnis.getText();
        } else if (rdEksekutif.isSelected()) {
            rdTipe = rdEksekutif.getText();
        }

        String ls_harga = txtHarga.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(dataConn, username, password);
            Statement state = con.createStatement();
            int result = state.executeUpdate("update data set maskapai = '" + ls_maskapai + "', dari = '" + ls_dari + "', menuju = '" + ls_menuju + "', berangkat = '" + ls_berangkat + "', tiba = '" + ls_tiba + "', tipe = '" + rdTipe + "', harga = '" + ls_harga
                    + "' where maskapai ='" + ls_maskapai + "' or dari ='" + ls_dari + "' or menuju ='" + ls_menuju + "' or berangkat ='" + ls_berangkat + "' or tiba = '"+ls_tiba+"' or tipe ='"+rdTipe+"' or harga = '"+ls_harga+"'");
            JOptionPane.showMessageDialog(this, "Data berhasil di ubah!");
            HalamanUtama1 halaman = new HalamanUtama1();
            this.setVisible(false);
            halaman.hapusdb();
            halaman.setVisible(true);
        } catch (SQLException e) {
            java.util.logging.Logger.getLogger(HalamanUtama1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HalamanUtama1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String ls_maskapai = cbMaskapai.getSelectedItem().toString();
        String ls_dari = cbDari.getSelectedItem().toString();
        String ls_menuju = cbMenuju.getSelectedItem().toString();
        String ls_berangkat = txtBerangkat.getText();
        String ls_tiba = txtTiba.getText();
        String rdTipe = "";
        if (rdEkonomi.isSelected()) {
            rdTipe = rdEkonomi.getText();
        } else if (rdBisnis.isSelected()) {
            rdTipe = rdBisnis.getText();
        } else if (rdEksekutif.isSelected()) {
            rdTipe = rdEksekutif.getText();
        }

        String ls_harga = txtHarga.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(dataConn, username, password);
            Statement state = con.createStatement();
            int result = state.executeUpdate("delete from data where maskapai ='" + ls_maskapai + "' and dari ='" + ls_dari + "' and menuju ='" + ls_menuju + "' and berangkat ='" + ls_berangkat + "'");
            JOptionPane.showMessageDialog(this, "Data berhasil di hapus!");
            HalamanUtama1 halaman = new HalamanUtama1();
            halaman.hapusdb();
            halaman.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HalamanUtama1 halaman = new HalamanUtama1();
        halaman.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbDari;
    private javax.swing.JComboBox<String> cbMaskapai;
    private javax.swing.JComboBox<String> cbMenuju;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdBisnis;
    private javax.swing.JRadioButton rdEkonomi;
    private javax.swing.JRadioButton rdEksekutif;
    private javax.swing.ButtonGroup rdTipe;
    private javax.swing.JTextField txtBerangkat;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtTiba;
    // End of variables declaration//GEN-END:variables
}
